export enum AllPrivileges {
  CAN_CREATE_STAFF = 'CAN_CREATE_STAFF',
  CAN_VIEW_DASHBOARD = 'CAN_VIEW_DASHBOARD',
  CAN_DELETE_USER = 'CAN_DELETE_USER',
  CAN_UPDATE_PROFILE = 'CAN_UPDATE_PROFILE',
  CAN_CREATE_ROLE = 'CAN_CREATE_ROLE',
  CAN_CREATE_PRIVILEGE = 'CAN_CREATE_PRIVILEGE',
  CAN_VIEW_USERS = 'CAN_VIEW_USERS',
  CAN_VIEW_USER_PROFILE = 'CAN_VIEW_USER_PROFILE',
  CAN_VIEW_PRIVILEGES = 'CAN_VIEW_PRIVILEGES',
  CAN_VIEW_ROLES = 'CAN_VIEW_ROLES',
  CAN_ASSIGN_PRIVILEGES = 'CAN_ASSIGN_PRIVILEGES',
  CAN_VIEW_RECEIVED_APPLICATIONS = 'CAN_VIEW_RECEIVED_APPLICATIONS',
  CAN_APPLY_FOR_JOB = 'CAN_APPLY_FOR_JOB',
  CAN_UPDATE_APPLICATION_STATUS = 'CAN_UPDATE_APPLICATION_STATUS',
  CAN_GET_INVOICES = 'CAN_GET_INVOICES',
  CAN_GET_PAYMENT_HISTORY = 'CAN_GET_PAYMENT_HISTORY',
  CAN_MAKE_PAYMENT = 'CAN_MAKE_PAYMENT',
  CAN_UPDATE_PROFILE_PRIVACY = 'CAN_UPDATE_PROFILE_PRIVACY',
  CAN_CREATE_ADMIN = 'CAN_CREATE_ADMIN',
  CAN_VIEW_ANY_APPLICATION = 'CAN_VIEW_ANY_APPLICATION',
  CAN_VIEW_ANALYTICS = 'CAN_VIEW_ANALYTICS',
  CAN_VIEW_ADMIN_DASHBOARD = 'CAN_VIEW_ADMIN_DASHBOARD',
  CAN_UPLOAD_ANY_IMAGE = 'CAN_UPLOAD_ANY_IMAGE',
  CAN_CREATE_INVOICE = 'CAN_CREATE_INVOICE',
}

export enum OtherStaff {}

export enum AdminPrivileges {}
